blank_issues_enabled: false
contact_links:
  - name: Aurora Project Board (internal)
    url: https://github.com/orgs/gccloudone-aurora/projects/1
    about: Internal SSC/partner roadmap and backlog (access required).
