name: Improvement / Feature
description: Suggest an improvement or request a new feature in Aurora.
title: "[Feature] <short summary here>"
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        🔖 Please follow our [Issue & PR Naming Conventions](https://aurora.gccloudone.alpha.canada.ca/team/standard-operating-procedures/issue-naming/).

  - type: textarea
    id: problem
    attributes:
      label: Problem / User Need
      description: What problem are you trying to solve?
      placeholder: Teams cannot discover curated images across departments without duplication.

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: Describe the change, key components, risks/alternatives.
      placeholder: Create a shared JFrog virtual repo that aggregates Chainguard images; add usage docs and examples.

  - type: input
    id: quarter
    attributes:
      label: Target Quarter
      description: Planned quarter (e.g., Q4 2025, Q1 2026). This will map to the Aurora Project iteration.
      placeholder: Q4 2025

  - type: input
    id: client
    attributes:
      label: Client / Partner
      description: Department, SSC Field, or Project Team this epic benefits (e.g., STC, SSC-Aurora).
      placeholder: STC

  - type: textarea
    id: success
    attributes:
      label: Success Criteria
      description: What outcomes or metrics define success?
      placeholder: |
        - [ ] Departments can pull curated images from SSC JFrog
        - [ ] Image updates are automated and reported
