FROM eclipse-temurin:21-jdk AS builder

WORKDIR /app

COPY src/main/java/com/example/*.java ./

RUN javac *.java

FROM eclipse-temurin:21-jre

WORKDIR /app

COPY --from=builder /app/*.class ./

EXPOSE 8080

CMD ["java", "App"]