FROM artifacts-artefacts.devops.cloud-nuage.canada.ca/ssc-spc.gc.ca/jre:openjdk-24.0.1

WORKDIR /app

COPY src/main/java/com/example/*.java ./

RUN javac *.java

FROM artifacts-artefacts.devops.cloud-nuage.canada.ca/ssc-spc.gc.ca/jdk:openjdk-24.0.1

WORKDIR /app

COPY --from=builder /app/*.class ./

EXPOSE 8080

CMD ["java", "App"]
