FROM artifacts-artefacts.devops.cloud-nuage.canada.ca/docker-chainguard-remote/ssc-spc.gc.ca/jdk@sha256:acda292df65f257b12de1e1b897a657d1fd5fbc665db94ad0d2e19b57251184f
WORKDIR /app
COPY src/main/java/com/example/*.java ./
RUN javac *.java

FROM artifacts-artefacts.devops.cloud-nuage.canada.ca/docker-chainguard-remote/ssc-spc.gc.ca/jre@sha256:f51e68324f1cc81a2fcaab2c7963286b46721327b3bdaadb8aeadef7ecd63473
WORKDIR /app
COPY --from=builder /app/*.class ./
EXPOSE 8080
CMD ["java", "App"]
