FROM artifacts-artefacts.devops.cloud-nuage.canada.ca/docker-chainguard-remote/ssc-spc.gc.ca/jdk@sha256:55e6c5d7738c7a65ace6793b5cc221fe73696fdb7408adebc9ab101bac09f962
WORKDIR /app
COPY src/main/java/com/example/*.java ./
RUN javac *.java

FROM artifacts-artefacts.devops.cloud-nuage.canada.ca/docker-chainguard-remote/ssc-spc.gc.ca/jre@sha256:a9573c39729b68eb1f1e3b9d702b615afcd406f307a0b69f68f71882ac4e6d86
WORKDIR /app
COPY --from=builder /app/*.class ./
EXPOSE 8080
CMD ["java", "App"]
