name: Simple Java Build and Security Scan

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "examples/java-app/**"
      - ".github/workflows/java-app.yml"
      - ".github/workflows/reusable-app-build.yml"
  pull_request:
    branches: [main]
    paths:
      - "examples/java-app/**"
      - ".github/workflows/java-app.yml"
      - ".github/workflows/reusable-app-build.yml"

jobs:
  build:
    uses: ./.github/workflows/reusable-app-build.yml
    permissions:
      id-token: write
      contents: read
      security-events: write
      pull-requests: write
    with:
      app: java-app
      language: Java
    secrets: inherit
