---
name: External/Fork Frogbot Pull Request Review

on:
  pull_request_target:
    types: [ opened, synchronize ]
    branches: [ main ]

permissions: read-all

env:
  JF_URL: "https://artifacts-artefacts.devops.cloud-nuage.canada.ca"
  JF_PROJECT: "ssc-aurora"

jobs:
  scan-pull-request:
    runs-on: ubuntu-latest
    environment: frogbot-external-review
    permissions:
      pull-requests: write
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false

      - name: Setup JFrog CLI with OIDC
        uses: jfrog/setup-jfrog-cli@v4
        id: setup-jfrog-cli
        env:
          JFROG_CLI_AVOID_NEW_VERSION_WARNING: "true"
        with:
          oidc-provider-name: github-oidc
          version: 2.91.0

      - name: Run Frogbot
        uses: jfrog/frogbot@v2
        env:
          JF_ACCESS_TOKEN: ${{ steps.setup-jfrog-cli.outputs.oidc-token }}
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JF_INCLUDE_ALL_VULNERABILITIES: "true"
          JF_FAIL: "true"


